library(constellatoR)
OGs <- "Orthogroups.tsv" # from orthofinder
GOsdir= "131species.eggnog" # the dir includes eggnog annotation results of all species
species <- c("Ampulex_compressa","Andrena_dorsata","Andrena_fulva","Andrena_haemorrhoa","Apis_cerana","Apis_florea","Apis_mellifera","Bombus_impatiens","Bombus_pyrosoma","Bombus_terrestris","Ceratina_calcarata","Eufriesea_mexicana","Frieseomelitta_varia","Habropoda_laboriosa","Holcopasites_calliopsidis","Melipona_quadrifasciata","Colletes_gigas","Hylaeus_anthracinus","Hylaeus_volcanicus","Cerceris_rybyensis","Ectemnius_continuus","Mimumesa_dahlbomi","Nysson_spinosus","Pemphredon_lugubris","Dufourea_novaeangliae","Lasioglossum_morio","Megalopta_genalis","Nomia_melanderi","Seladonia_tumulorum","Sphecodes_monilicornis","Anthidium_xuezhongi","Megachile_rotundata","Osmia_bicornis","Osmia_lignaria","Stelis_phaeoptera","Macropis_europaea","Chelonus_insularis","Cotesia_glomerata","Cotesia_sesamiae","Diachasma_alloeum","Fopius_arisanus","Habrobracon_hebetor","Macrocentrus_cingulum","Microctonus_hyperodae","Microplitis_demolitor","Microplitis_mediator","Amblyteles_armatorius","Buathra_laborator","Diadromus_collaris","Apanteles_cypris","Aphidius_gifuensis","Binodoxys_communis","Cotesia_chilonis","Microctonus_aethiopoides","Ichneumon_xanthorius","Ophion_luteus","Venturia_canescens","Cephus_cinctus","Ceratosolen_solmsi","Eupristina_verticillata","Eretmocerus_hayati","Copidosoma_floridanum","Chouioia_cunea","Anastatus_fulloi","Anastatus_japonicus","Anisopteromalus_calandrae","Nasonia_vitripennis","Pachycrepoideus_vindemmiae","Pteromalus_puparum","Pteromalus_qinghaiensis","Pteromalus_venustus","Theocolax_elegans","Trichomalopsis_sarcophagae","Trichogramma_pretiosum","Gonatopus_flavifemur","Belonocnema_kinseyi","Leptopilina_boulardi","Leptopilina_heterotoma","Acromyrmex_charruanus","Acromyrmex_echinatior","Acromyrmex_insinuator","Atta_colombica","Camponotus_floridanus","Cataglyphis_hispanica","Cyphomyrmex_costatus","Dinoponera_quadriceps","Eciton_burchellii","Formica_exsecta","Harpegnathos_saltator","Linepithema_humile","Monomorium_pharaonis","Nylanderia_fulva","Odontomachus_brunneus","Ooceraea_biroi","Pogonomyrmex_barbatus","Pseudoatta_argentina","Pseudomyrmex_gracilis","Solenopsis_invicta","Temnothorax_curvispinosus","Temnothorax_longispinosus","Trachymyrmex_cornetzi","Trachymyrmex_septentrionalis","Trachymyrmex_zeteki","Vollenhovia_emeryi","Wasmannia_auropunctata","Orussus_abietinus","Telenomus_remus","Anoplius_nigerrimus","Diprion_similis","Neodiprion_fabricii","Neodiprion_lecontei","Neodiprion_virginianus","Athalia_rosae","Rhogogaster_chlorosoma","Tenthredo_mesomela","Tenthredo_notha","Tiphia_femorata","Polistes_dominula","Vespa_crabro","Polistes_canadensis","Vespula_pensylvanica","Vespula_vulgaris","Polistes_fuscatus","Vespa_mandarinia","Vespa_velutina","Dolichovespula_media","Dolichovespula_saxonica","Dolichovespula_sylvestris","Vespula_germanica","Ancistrocerus_nigricornis","Mischocyttarus_mexicanus")

GOsfromOGs <- prepareGOsfromOGs(OGs, GOsdir, species = species,cores=28)
selected_OGs <- c("OG0009248", "OG0009250", ..., "OG0009269", "OG0009271")
semSim <- getSemSim(GOsfromOGs = GOsfromOGs, selectedOGs = selected_OGs)
simMat <- getSimMat(GOsfromOGs = GOsfromOGs, selectedOGs = selected_OGs, semSim = semSim)
clusters <- clusterOGs(simMat)
write.table(clusters, 'clusters.txt', col.names = NA, sep = '\t', quote = FALSE)